### ISSUE TITLE
[bug] Hosted Gorilla misinterpreted the requirement 

### ISSUE THREAD

**Issue by ravindrakr** [ShishirPatil/gorilla#100]
**Describe the bug**
Gorilla misinterpreted the requirement as a video classifier when I clearly gave instructions that it is not a video classification app but a 1-1 video calling app.

**To Reproduce**
Use the following prompt:
prompt = "I want to build a one-to-one video calling application for web and pwa. This is NOT a classification app. Please provide code snippets"
print(get_gorilla_response(prompt, model="gorilla-7b-hf-v0"))

**Screenshots**
![image](https://github.com/ShishirPatil/gorilla/assets/1014591/1ecfa143-57a8-44a5-9f3b-421c5581fa5f)

**Comment by ShishirPatil** [comment]
Thanks for highlighting this @ravindrakr The `gorilla-7b-hf-v0` picks from among the models available on hugging-face (hence the `hf`). So, it is likely to not find one for you intended task. I would recommend using the `gorilla-cli` which can be installed with `pip install gorilla-cli` which has a much richer and diverse set of APIs. Thanks!

**Comment by ravindrakr** [comment]
Hi Shishir,

Thanks for the suggestion. I'll try using the gorilla-cli and see if it
works better for my task.

Best,
Ravindra
