### ISSUE TITLE
[feature]  Gradio webui

### ISSUE THREAD

**Issue by TanmayDoesAI** [ShishirPatil/gorilla#102]
**Is the feature request related to a problem?**
Okay, so I explored the colab notebook, and it was fairly easy to use, But the thing is the current crowd is used to having a gradio webui. I have made a github repo for the same, you could have a look:
[Gradio Webui](https://github.com/TanmayDoesAI/Gorilla-WebUI)

This makes it not just easier to classify each output of the model, but gives us an easy way to just copy the code for further usage
![Gorilla Colab WebUI](https://github.com/TanmayDoesAI/Gorilla-WebUI/assets/85993243/f167f774-8eef-4e02-aa55-0436c9e4547d)

**Comment by ShishirPatil** [comment]
Hey @TanmayDoesAI This is phenomenal! Yeah I agree that this is a great UI to use! Do you mind raising a PR? 
Also, one minor suggestion might be to give the users an option of picking which model they want as an input. It could be a radio button / drop down etc. You are much better at UI then I am, so I trust your instincts on this one :) 

Thanks again man! Cool work.

**Comment by TanmayDoesAI** [comment]
Thanks a lot for the positive feedback! I'm excited that you liked the Gradio WebUI idea. Adding model selection through dropdown sounds cool, I'll definitely include that. I'll get to work on the changes and submit a PR soon. Your encouragement means a ton.
