### ISSUE TITLE
How do i integrate gorilla LLM into AutoGPT?

### ISSUE THREAD

**Issue by Swarde11** [ShishirPatil/gorilla#104]
they just said that you can integrate the LLM into AutoGPT, and gorilla LLM beats GPT-4, but i really want to integrate it, any help?

*if you answered, then thank you*

**Comment by solomon8392** [comment]
Yes, it is possible to integrate an LLM into AutoGPT. There are a few ways to do this:
You can modify the code to accept a config file as input, and read the Chosen_Model flag to select the appropriate AI model,
and You can use an API wrapper to access the LLM. There are a number of API wrappers available, such as the Hugging Face Transformers library, and then You can host the LLM yourself.

**Comment by solomon8392** [comment]
Okay just follow this steps,
Install the Gorilla LLM and AutoGPT Python packages. and when it's done installing, you
Create a new Python file and import the Gorilla and AutoGPT modules. Once you are done creating you Create a Gorilla model object and an AutoGPT model object, and you now Set the Gorilla model as the default model for the AutoGPT model. the Use the AutoGPT model to generate text. and this is the pre Example of how the code will be.


import gorilla
import autogpt

# Create a Gorilla model object
model = gorilla.Model()

# Create an AutoGPT model object
gpt = autogpt.GPT()

# Set the Gorilla model as the default model for the AutoGPT model
gpt.set_default_model(model)

# Generate text using the AutoGPT model
text = gpt.generate("This is a sentence generated by AutoGPT with Gorilla LLM.")

print(text)

So with you following all this steps you are good to go

**Comment by solomon8392** [comment]
please if you have any question let me know Okay
