### ISSUE TITLE
Replicate the results in paper

### ISSUE THREAD

**Issue by Boyu-Mi** [ShishirPatil/gorilla#118]
I ran the following command in `eval/eval-scripts` dir 

```bash
python ast_eval_hf.py     \
    --api_dataset ../../data/api/huggingface_api.jsonl     \
    --apibench ../../data/apibench/huggingface_eval.json     \
    --llm_responses ../eval-data/responses/huggingface/response_huggingface_Gorilla_FT_oracle.jsonl 
```

And got the results:
```
Final Functionality accuracy:  0.4446902654867257
Final hallucination:  0.5276548672566371
```

It seems not to match any results in Gorilla's paper. What command should I use to replicate the results? Thanks.

**Comment by ShishirPatil** [comment]
Thanks for trying out Gorills @Boyu-Mi As discussed in https://github.com/ShishirPatil/gorilla/issues/56 the Paper is a snapshot in time, the repository has evolved ahead :)
