### ISSUE TITLE
[Apibench] Some questions about data generation.

### ISSUE THREAD

**Issue by siyilingting** [ShishirPatil/gorilla#125]
Thinks for your sharing, I have some questions about generating data:
1. What are the 18 hand-generated  in-context examples for the three model hubs？Are there any tendencies when you construct them? For example, select some APIs in a centain domain or even a certain API.
2. How are the contents of the \<\<\<explanation\>\>\> and \<\<\<code\>\>\> components generated? Are they generated by GPT4 based on three random hand-generated in-context examples?

**Comment by ShishirPatil** [comment]
Hey @siyilingting 

1. We haven't yet open sourced the hand-generated in-context examples. 
2. Yes and no! They are generated by GPT, but not based just on in-context examples, but more critically with the documentation of the APIs in-context. 

Hope this helps! Let me know if you have any other questions!

**Comment by Shahad-Mohammed** [comment]
Thank you for the explanation but how are the <<<explanation>>> and <<<code>>> components generated by the documentation of the APIs in-context?
