### ISSUE TITLE
Error occurs when batch Inference using gorilla-mpt-7b-hf-v0

### ISSUE THREAD

**Issue by siyilingting** [ShishirPatil/gorilla#126]
1) When I run
`python gorilla_eval.py --model-path ./gorilla-mpt-7b-hf-v0/ --question-file ./example_questions/example_questions.jsonl --answer-file ./tmp.jsonl`
a ValueError occurs:
`ValueError: Tokenizer class GPTNeoXTokenizer does not exist or is not currently imported.`
<img width="200" alt="image" src="https://github.com/ShishirPatil/gorilla/assets/23379451/abf86f7e-6aa9-4faf-9dca-6b9ad5532f64">

2) If I set `use_fast=True` in `AutoTokenizer.from_pretrained` and `trust_remote_code=True` in `AutoModelForCausalLM.from_pretrained`, the model  can be loaded but another error occurs:
`AssertionError: Cannot forward input with seq_len=2049, this model only supports seq_len<=2048`

I have created a conda virtual environment and installed the dependencies according to the [readme](https://github.com/ShishirPatil/gorilla/blob/main/inference/README.md#install-dependencies). So how to solve the problems.

**Comment by ShishirPatil** [comment]
Hey @siyilingting thank you for your interest! Yes, you need to `use_fast=True` in `AutoTokenizer.from_pretrained` and `trust_remote_code=True` in `AutoModelForCausalLM.from_pretrained`. Now, coming to the token length, you can clip the tokens to 2048.
