### ISSUE TITLE
[bug] Hosted Gorilla: <Issue>

### ISSUE THREAD

**Issue by SpinNeutron** [ShishirPatil/gorilla#132]
While trying the example notebook I get the following errors:

With the default api base:

Exception: Error communicating with OpenAI: HTTPConnectionPool(host='zanino.millennium.berkeley.edu', port=8000): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e590023a110>: Failed to establish a new connection: [Errno 111] Connection refused'))
Failed model: gorilla-7b-hf-v1, for prompt: I would like to translate 'I feel very good today.' from English to Chinese

With the alternate mirror:

Exception: HTTP code 502 from API (<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>
)
Failed model: gorilla-7b-hf-v1, for prompt: I would like to translate 'I feel very good today.' from English to Chinese

**Comment by ShishirPatil** [comment]
Thanks for raising this @SpinNeutron  The provider shut down the Gorilla server for scheduled maintenance, and is now up!
