### ISSUE TITLE
[bug] Hosted Gorilla: <Issue>

### ISSUE THREAD

**Issue by TaoAthe** [ShishirPatil/gorilla#134]
Exception: Error communicating with OpenAI: HTTPConnectionPool(host='zanino.millennium.berkeley.edu', port=8000): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a33981022f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Failed model: gorilla-7b-hf-v1, for prompt: I would like to translate 'I feel very good today.' from English to Chinese

**Comment by ShishirPatil** [comment]
Thanks for raising this @TaoAthe The provider shut down the Gorilla server for scheduled maintenance, and is now up!
