### ISSUE TITLE
[bug] Hosted Gorilla: <Issue>

### ISSUE THREAD

**Issue by siisee11** [ShishirPatil/gorilla#15]
Exception: Error communicating with OpenAI: HTTPConnectionPool(host='34.132.127.197', port=8000): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f912081fb50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Failed model: gorilla-7b-hf-v0, for prompt: I would like to translate from English to Chinese

**Comment by ShishirPatil** [comment]
Sorry for this, I was just updating that back end server. It should now be fixed :)

**Comment by siisee11** [comment]
Thank you for your fast reply! 👍🏻
