### ISSUE TITLE
Location of gorilla-cli

### ISSUE THREAD

**Issue by gilv** [ShishirPatil/gorilla#151]
There is a project [https://github.com/gorilla-llm/gorilla-cli](https://github.com/gorilla-llm/gorilla-cli) with gorilla-cli. 
But there is gorilla-cli inside gorilla project as well [https://github.com/ShishirPatil/gorilla/blob/main/inference/serve/gorilla_cli.py](https://github.com/ShishirPatil/gorilla/blob/main/inference/serve/gorilla_cli.py). 

Which one is the right location of gorilla-cli?

**Comment by ShishirPatil** [comment]
Hey @gilv The [gorilla-cli](https://github.com/gorilla-llm/gorilla-cli) contains all the code for the client and the "app" which hits the hosted-endpoint. The gorilla-cli file inside the main gorilla repository is just for local inference of the model.
