### ISSUE TITLE
eval resutls

### ISSUE THREAD

**Issue by Wangpeiyi9979** [ShishirPatil/gorilla#17]
Hi, thanks for your excellent work.

I ran the eval-scrip
```
python ast_eval_th.py --api_dataset ../../data/api/torchhub_api.jsonl --apibench ../../data/apibench/torchhub_eval.json --llm_responses ../eval-data/responses/torchhub/response_torchhub_Gorilla_FT_0_shot.jsonl
```

and get the results:

```
Final Functionality accuracy:  0.7580645161290323
Final hallucination:  0.16129032258064516
```
I find these results are inconsistent with the results reported in the paper.

![image](https://github.com/ShishirPatil/gorilla/assets/42565075/54bca112-2035-4d9e-898e-c1fb91c50374)

I would like to ask where I got it wrong. 

Thanks.

**Comment by ShishirPatil** [comment]
HI @Wangpeiyi9979 thanks for the pointer. When we OSS, we further cleaned up the data which reflects in the improved performance - the code/pipeline remains same. Our plan was to update the paper in the camera ready if it gets accepted, or in the subsequent submission :crossed_fingers:

Feel free to reopen the issue if you have any follow-up questions!
