### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by wooters** [ShishirPatil/gorilla#2]
Hello, thanks for making your work available! Have you chosen a license yet?

**Comment by ShishirPatil** [comment]
Hi @wooters Thank you for your kind words, and you raise a very important question. We're presently in the process of determining the most suitable license for this project, one that would foster a welcoming environment for API contributors, model developers, and the community.
As we continue to deliberate on this, I'll keep this issue open. In the meantime, we would be thrilled to hear any thoughts or suggestions that you or others in the community may have on this matter.

**Comment by jpzhangvincent** [comment]
Since the base LLM model is LLaMA, it seems it's not permitted for commercial use, right? Have you thought of fine-tuning on top of Open-LLaMA/ Dolly/ StableLM instead?

**Comment by ShishirPatil** [comment]
Hi @jpzhangvincent thanks for bringing this up! Yes indeed, we are planning on fine-tuning a model that is permitted for commercial use. We will update the Project Roadmap on the README with the expected release date soon!

**Comment by ShishirPatil** [comment]
Thanks @wooters @jpzhangvincent and everyone for the discussion. Gorilla is Apache 2.0. With #38 we now have models based on MPT-7B and Falcon-7B which are Apache 2.0.
