### ISSUE TITLE
Simple OpenAI Function Calling sample does not return correct answer

### ISSUE THREAD

**Issue by ChristianWeyer** [ShishirPatil/gorilla#246]
Hey all,

I am using the public endpoint at http://luigi.millennium.berkeley.edu:8000.

Now I am trying to execute an example I took from the OpenAI docs:

```
curl http://luigi.millennium.berkeley.edu:8000/v1/chat/completions \
-H "Content-Type: application/json" \
-d '{
  "model": "gorilla-openfunctions-v2",
  "messages": [
    {
      "role": "user",
      "content": "What is the weather like in Boston?"
    }
  ],
  "tools": [
    {
      "type": "function",
      "function": {
        "name": "get_current_weather",
        "description": "Get the current weather in a given location",
        "parameters": {
          "type": "object",
          "properties": {
            "location": {
              "type": "string",
              "description": "The city and state, e.g. San Francisco, CA"
            },
            "unit": {
              "type": "string",
              "enum": ["celsius", "fahrenheit"]
            }
          },
          "required": ["location"]
        }
      }
    }
  ],
  "tool_choice": "auto"
}'
```

What I get back is not what I expected:

`{"id":"chatcmpl-dxmbzPzuBnGEt2T2mzNezD","object":"chat.completion","created":1709820314,"model":"gorilla-openfunctions-v2","choices":[{"index":0,"message":{"role":"assistant","content":"Apologies for any confusion, but as an AI developed by OpenAI, I'm designed to answer questions related to computer science and programming. I don't have real-time capabilities or access to external databases to provide the current weather forecast. Please use a reliable weather forecasting service or app to get the current weather conditions in your area.","function_call":null},"finish_reason":"stop"}],"usage":{"prompt_tokens":477,"total_tokens":547,"completion_tokens":70}}`

Any idea what is wrong?

Thanks!

**Comment by tianjunz** [comment]
Hi Christian, thanks for your interest! We have just updated the local inference and host inference scripts here: https://github.com/ShishirPatil/gorilla/tree/main/openfunctions. Could you give it a try and let us know if this works or not? Thanks!

**Comment by ChristianWeyer** [comment]
Hey @tianjunz - thanks for the answer.

I am not sure how the updated scripts affect my original inquiry :-).

I am doing a simple curl against the berkeley.edu endpoint (see above). And that one fails.

Any ideas?
Thanks!
