### ISSUE TITLE
timeline to release training codes?

### ISSUE THREAD

**Issue by Jeffwan** [ShishirPatil/gorilla#25]
Thanks for sharing the awesome work!  do you have a rough estimate when will be you release the training codes?

**Comment by ShishirPatil** [comment]
Thanks for your kind words @Jeffwan and your interest. Yes, the Project Timeline is here: https://github.com/ShishirPatil/gorilla/blob/main/README.md#project-roadmap

**Comment by dongs0104** [comment]
@ShishirPatil Hello, the README has been changed, when are you going to release training code?

**Comment by johnjiangxt** [comment]
@ShishirPatil , how many GPU as well as GPU type do you need to train a gorilla model?
