### ISSUE TITLE
[Leaderboard] the model is not redirected to its provenance webpage...

### ISSUE THREAD

**Issue by zhimin-z** [ShishirPatil/gorilla#270]
Check https://gorilla.cs.berkeley.edu/leaderboard.html#leaderboard but found:
<img width="1128" alt="1710713496152" src="https://github.com/ShishirPatil/gorilla/assets/8592144/a3d0a065-bd57-4392-9a9d-f907ce691468">
It does not redirect but it is in fact clickable...

**Comment by ShishirPatil** [comment]
Hey @zhimin-z this is now fixed. Thank you very much for flagging this!
