### ISSUE TITLE
[feature] Adding more type annotations for the raft project

### ISSUE THREAD

**Issue by UponTheSky** [ShishirPatil/gorilla#282]
**Is the feature request related to a problem?**
I hope there are more type annotations for the functions in the raft project(`raft` directory).

**Describe the solution you'd like**
Adding type annotations for the function parameters and return values will significantly improve code readability when using IDEs like VSCode. Since the Python interpreter doesn't do type checking at runtime, adding type annotations will not change any current behaviors of the codebase.

There are a few annotations already, but many of the parameters are still unannotated.
I made a PR for this issue as well, so please have a look. I hope this helps.

**Comment by ShishirPatil** [comment]
Closed with #283 Thank you!
