### ISSUE TITLE
Does the Gorilla open functions v2 model need to be fused with the Deepseek Coder-7B-Instrument-v1.5 model before it can be used for inference?

### ISSUE THREAD

**Issue by wangbochao1** [ShishirPatil/gorilla#294]
Does the Gorilla open functions v2 model need to be fused with the Deepseek Coder-7B-Instrument-v1.5 model before it can be used for inference?

**Comment by ShishirPatil** [comment]
Nope. This is not a delta, neither a LoRA adapter. Can be used directly! Let us know if you run into any issues!
