### ISSUE TITLE
Prompt Template to Finetune Mistral Model

### ISSUE THREAD

**Issue by chaser06** [ShishirPatil/gorilla#334]
I am trying to finetune the 'mistralai/Mistral-7B-Instruct-v0.1' model using peft and I am not able to find a proper prompt template for the training. I have already generated the RAFT dataset using the 'RAFTDatasetPack' from llamaindex. 

Column names in the dataset are: ['id', 'type', 'question', 'context', 'oracle_context', 'cot_answer', 'instruction']
My doubt is how to use various columns to generate the prompt template for the training. From what I have understood, the 'instruction' column should be given as input and 'cot_answer' should be given as response?

I have not found any proper training guide for RAFT other than azure-ai-studio, any help would be really appreciated!!
If you need any more clarifications, please let me know

**Comment by ShishirPatil** [comment]
Hey @chaser06 Thanks for trying out RAFT! You are right, the instruction column is the input and the `cot_answer` should be response. Although just make sure the instruction column is not JUST generic instruction, but also is concatenated with the prompt / question for each data-point. If you have an example perhaps, I can give you more information. 

The tutorial is here: https://github.com/ShishirPatil/gorilla/blob/main/raft/azure-ai-studio-ft/howto.md

**Comment by tien-tran0906** [comment]
Hello @ShishirPatil, I want to revisit this just to make sure I'm setting up the finetuning data correctly. Same issue with the above, I'm finetuning mistralai/Mistral-7B-Instruct-v0.1.

I have a sample dataset here on HuggingFace that were generated using your raft.py:
https://huggingface.co/datasets/Tien09/RAFT_dataset_test?row=2

And in the MS Build conference, where you got the jsonl file in Jupyter Notebook (with 7 columns),  I still don't understand the part where you converted it into 2 columns of 'text' and 'ground_truth' to put into finetuning:
https://build.microsoft.com/en-US/sessions/78e4ef86-4443-4cb6-a0b4-157a6623fe87

I understand the 'CoT' column is renamed to 'ground_truth' in your finetuning dataset. But in the 'text' column, I'm just a little confused of how would you concatenate everything else together? 

I made a sample finetuning dataset here, derived from the RAFT_dataset_test above, but concatenate 'instruction' + 'context' + 'question' together to make 'test', and with delimiter like '### Question' and '### Context':
https://huggingface.co/datasets/Tien09/RAFT_output_modified

Let me know if this format looks correct.
