### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by thisismygitrepo** [ShishirPatil/gorilla#349]
I did a fresh local installation then ran `goex -h` only to get this:

```
Traceback (most recent call last):
  File "/home/alex/venvs/goex/bin/goex", line 5, in <module>
    from cli import main
  File "/home/alex/code/foreign/gorilla/goex/cli.py", line 9, in <module>
    from authorizations.scripts.authorization_utils import authorize_service
ModuleNotFoundError: No module named 'authorizations'
```

Can we make it like `from goex import authorizations` to avoid this? or make it relative import.

**Comment by royh02** [comment]
Hi @thisismygitrepo! Thanks for bringing this issue to light. Can you elaborate on what installation steps you took that led you here?

**Comment by thisismygitrepo** [comment]
I cloned the repo,

```
python3 -m venv goex-env
source goex-env/bin/activate
# cd to clone dir then goex then:
pip install -e .
```
as per official [readme](https://github.com/ShishirPatil/gorilla/tree/main/goex)

**Comment by royh02** [comment]
@thisismygitrepo Can you try to see if this PR fixes your issue? Thanks for catching this bug when the venv is created in a different location.

**Comment by royh02** [comment]
The changes are now live @thisismygitrepo , can you try to pull again, `pip uninstall goex`, and see if the issue remains when u reinstall?

**Comment by thisismygitrepo** [comment]
Thanks. That was an easier solution than mine. 🚀
