### ISSUE TITLE
[Demo UI/UX Improvement] GoEX Demo UI/UX

### ISSUE THREAD

**Issue by CharlieJCJ** [ShishirPatil/gorilla#362]
Hey GoEX team, great work!

I was trying this demo https://goex.gorilla-llm.com/index, and had another small suggestion on the UX,
<img width="1123" alt="image" src="https://github.com/ShishirPatil/gorilla/assets/55744150/b577834b-2d55-4385-845b-3b02d43bc2a9">
If a registered user has filled out the vote, the second time one clicks on the `Submit Vote` button, it should pop up an error message saying they had voted. Right now, even though there is an expected increment in votes after the user has voted and expected no change in votes when the user submitted a vote more than 1 time, the button triggers refresh on the page without prompting the user that the vote is successful or not successful, which isn't ideal. Thanks!

**Comment by opatothan** [comment]
Thanks for raising this issue! The idea was for users to be able to recast votes if they change their mind or want to add a new service. If you vote for NewsAPI, it should add one vote to NewsAPI, and if you uncheck that vote then submit vote again it should remove your vote. I changed the button to make it more clear that votes are being recast.
