### ISSUE TITLE
Running BFCL data on Cohere

### ISSUE THREAD

**Issue by shashi792** [ShishirPatil/gorilla#378]
I am trying to run the BFCL on cohere's command+r model. While running everything in pipeline is a later task. For now, I am trying to search the function - evaluators. 

E.g.  

`test-executable-simple.json` File. 

`{
    "question": "In a game of dice, a player rolls a die 20 times. If the probability of rolling a 6 is 0.6, what is the probability that the player will roll a 6 exactly 5 times?",
    "function":
    {
        "name": "calc_binomial_probability",
        "description": "Calculates the probability of getting k successes in n trials.",
        "parameters":
        {
            "type": "dict",
            "properties":
            {
                "n":
                {
                    "type": "integer",
                    "description": "The number of trials."
                },
                "k":
                {
                    "type": "integer",
                    "description": "The number of successes."
                },
                "p":
                {
                    "type": "float",
                    "description": "The probability of success."
                }
            },
            "required":
            [
                "n",
                "k",
                "p"
            ]
        }
    },
    "execution_result":
    [
        0.0012944935222876579
    ],
    "execution_result_type": "exact_match"
}`

Where can I find the executor-function for the above function?.

**Comment by HuanzhiMao** [comment]
Hi there, 
All the executable functions are in  `berkeley-function-call-leaderboard/eval_checker/executable_python_function.py`. For example, the one you mentioned above is at [https://github.com/ShishirPatil/gorilla/blob/main/berkeley-function-call-leaderboard/eval_checker/executable_python_function.py#L189-L201](https://github.com/ShishirPatil/gorilla/blob/main/berkeley-function-call-leaderboard/eval_checker/executable_python_function.py#L189-L201)
