### ISSUE TITLE
integrating discord webhooks with Repo

### ISSUE THREAD

**Issue by Gooferball69** [ShishirPatil/gorilla#4]
This would allow discord members to easily view GitHub commits/Issues/Pull Requests easily.
I wouldn't mind having access having access to certain settings in this Repo in order to set it up.
If you don't want to give perms you can use this guide here https://ardalis.com/integrate-github-and-discord-with-webhooks/

**Comment by ShishirPatil** [comment]
Hi @Gooferball69 Thanks for the pointer. This is done and it points to the #github-updates channel on the Gorilla Discord.

**Comment by Gooferball69** [comment]
@ShishirPatil 
It seems you an commit 20 mins ago and the discord bot did not pick up on the commit.
