### ISSUE TITLE
Sql and chatable eval

### ISSUE THREAD

**Issue by sebastiangonsal** [ShishirPatil/gorilla#408]
The sql and chatable evals are not done for leaderboard but there is data for both those categories in the dataset so I am guessing there is some eval code somewhere. How can I run the sql and chatable evals ?

**Comment by HuanzhiMao** [comment]
Hi @sebastiangonsal, 
To run the SQL and Chatable evals, you need to slightly modify our current evaluation pipeline. 
You need to first comment out these three lines. [https://github.com/ShishirPatil/gorilla/blob/main/berkeley-function-call-leaderboard/eval_checker/eval_runner.py#L321-L323](https://github.com/ShishirPatil/gorilla/blob/main/berkeley-function-call-leaderboard/eval_checker/eval_runner.py#L321-L323). Then for SQL, you want to use `single_ast_file_runner` function for evaluation. And for chatable, you can use the `single_relevance_file_runner` function; it's the same logic as the relevance detection test.
Let me know if you have more questions!
