### ISSUE TITLE
[bug] LlamaHandler format

### ISSUE THREAD

**Issue by justinwangx** [ShishirPatil/gorilla#430]
I think there is a bug in the way formatting is handled for Llama models [here](https://github.com/ShishirPatil/gorilla/blob/main/berkeley-function-call-leaderboard/model_handler/llama_handler.py#L13) in this function:

```python
def _format_prompt(prompt, function, test_category):
    conversations = f"""<|begin_of_text|><|start_header_id|>system<|end_header_id|>{SYSTEM_PROMPT_FOR_CHAT_MODEL}<|eot_id|><|start_header_id|>user<|end_header_id|>{USER_PROMPT_FOR_CHAT_MODEL.format(user_prompt=prompt, functions=str(function))}<|eot_id|><|start_header_id|>assistant<|end_header_id|>"""
    return conversations
```

Given placeholder system and user messages, if I use the Llama-3 tokenizer as follows:

```python
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("meta-llama/Meta-Llama-3-8B-Instruct")
messages = [
    {"role": "system", "content": "SYSTEM"},
    {"role": "user", "content": "USER"}
]
conversations = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
print(conversations)
```

then I get the following output:

```python
'<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\nSYSTEM<|eot_id|><|start_header_id|>user<|end_header_id|>\n\nUSER<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n'
```

The current format misses the "\n\n" which appears after the end of each header id.

**Comment by CharlieJCJ** [comment]
Thank you for catching this! This is indeed an oversight on our end. 

Right now, we observe minor improvements to both llama3-8b and llama3-70b models, not affecting their position on the leaderboard. We will verify the results and address this issue in the next release by updating the handler alongside leaderboard scores on llama3 results, making llama handler's prompt template consistent with the official one. Thanks again!

**Comment by justinwangx** [comment]
No problem! Awesome -- thanks for your great work on this benchmark.

I have another (mostly unrelated) question as well -- are the benchmark numbers reported when running with temperature=0? I was unable to reproduce the scores for Llama-3-8B-Instruct and noticed the default temperature setting was 0.7.

**Comment by justinwangx** [comment]
Also -- I want to do local inference with gorilla-llm/gorilla-openfunctions-v2, and it seems that there is a discrepancy between the prompt formatting in the [inference_local.py](https://github.com/ShishirPatil/gorilla/blob/main/openfunctions/inference_local.py) file and how formatting is handled with the model's tokenizer.

Using the setup in the example file:

```python
import json

def get_prompt(user_query: str, functions: list = []) -> str:
    """
    Generates a conversation prompt based on the user's query and a list of functions.

    Parameters:
    - user_query (str): The user's query.
    - functions (list): A list of functions to include in the prompt.

    Returns:
    - str: The formatted conversation prompt.
    """
    system = "You are an AI programming assistant, utilizing the Gorilla LLM model, developed by Gorilla LLM, and you only answer questions related to computer science. For politically sensitive questions, security and privacy issues, and other non-computer science questions, you will refuse to answer."
    if len(functions) == 0:
        return f"{system}\n### Instruction: <<question>> {user_query}\n### Response: "
    functions_string = json.dumps(functions)
    return f"{system}\n### Instruction: <<function>>{functions_string}\n<<question>>{user_query}\n### Response: "
    
query_1: str = "What's the weather like in the two cities of Boston and San Francisco?"
functions_1 = [
    {
        "name": "get_current_weather",
        "description": "Get the current weather in a given location",
        "parameters": {
            "type": "object",
            "properties": {
                "location": {
                    "type": "string",
                    "description": "The city and state, e.g. San Francisco, CA",
                },
                "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]},
            },
            "required": ["location"],
        },
    }
]

prompt_1 = get_prompt(query_1, functions=functions_1)
```

the value of `prompt_1` is:

```
You are an AI programming assistant, utilizing the Gorilla LLM model, developed by Gorilla LLM, and you only answer questions related to computer science. For politically sensitive questions, security and privacy issues, and other non-computer science questions, you will refuse to answer.
### Instruction: <<function>>[{"name": "get_current_weather", "description": "Get the current weather in a given location", "parameters": {"type": "object", "properties": {"location": {"type": "string", "description": "The city and state, e.g. San Francisco, CA"}, "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]}}, "required": ["location"]}}]
<<question>>What's the weather like in the two cities of Boston and San Francisco?
### Response:
```

However, if I run the following in an attempt to match the above formatting:

```python
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("gorilla-llm/gorilla-openfunctions-v2")
TEMPLATE = """"<<function>>{function}\n<<question>>{prompt}"""
messages = [
    {"role": "user", "content": TEMPLATE.format(function=str(functions_1), prompt=query_1)}
]
print(tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True, add_special_tokens=False))
```

then the result is:

```
### Instruction:
<<function>>[{'name': 'get_current_weather', 'description': 'Get the current weather in a given location', 'parameters': {'type': 'object', 'properties': {'location': {'type': 'string', 'description': 'The city and state, e.g. San Francisco, CA'}, 'unit': {'type': 'string', 'enum': ['celsius', 'fahrenheit']}}, 'required': ['location']}}]
<<question>>What's the weather like in the two cities of Boston and San Francisco?
### Response:
```

Specifically, there is a new line character after `### Instruction:` when using the tokenizer's chat template.

I'm curious how the model was trained and which prompt format is correct.

**Comment by CharlieJCJ** [comment]
> No problem! Awesome -- thanks for your great work on this benchmark.
> 
> I have another (mostly unrelated) question as well -- are the benchmark numbers reported when running with temperature=0? I was unable to reproduce the scores for Llama-3-8B-Instruct and noticed the default temperature setting was 0.7.

We are using `temperature = 0.7` for reported llama3 numbers. If you would like to provide more information on what is different, we can investigate why you are not able to reproduce.

**Comment by justinwangx** [comment]
If we are sampling but not seeding, then results will naturally not be deterministic. There is some unavoidable non-determinism that vLLM introduces, but I imagine most of the discrepancy stems from sampling with non-zero temperature.

**Comment by HuanzhiMao** [comment]
`temperature` is changed to 0.001 in #574
