### ISSUE TITLE
[bug] Hosted Gorilla: Expired HTTPS certificate

### ISSUE THREAD

**Issue by davidlj95** [ShishirPatil/gorilla#436]
**Describe the bug**
CLI fails when using hosted Gorilla

**To Reproduce**
`gorilla whatever`

Returns

```
⠼ LoadingServer is unreachable.
Try updating Gorilla-CLI with 'pip install --upgrade gorilla-cli'
```

Turns out certificate at `cli.gorilla-llm.com` expired yesterday:

```
Expires On: Sunday 19 May 2024 at 22:44:39
```

**Screenshots**
N/A

**Proposed Solution**
Update the certificate 😛 

**Additional context**

**Comment by bdmorin** [comment]
posted a hack to make it work here: 
https://github.com/gorilla-llm/gorilla-cli/issues/60#issuecomment-2125402761

**Comment by ShishirPatil** [comment]
Thank you @davidlj95 and @bdmorin. This is now fixed.

**Comment by abitrolly** [comment]
@ShishirPatil unfortunately, it is not.

```bash
$ curl https://cli.gorilla-llm.com   
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the webpage mentioned above.
```
