### ISSUE TITLE
[bug] Hosted Gorilla: <Issue>

### ISSUE THREAD

**Issue by vsionary14** [ShishirPatil/gorilla#44]
Exception: Error communicating with OpenAI: HTTPConnectionPool(host='34.132.127.197', port=8000): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f455ea077f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Failed model: gorilla-7b-hf-v0, for prompt: I would like to translate from English to Chinese

**Comment by ShishirPatil** [comment]
Thanks for raising this @vsionary14 The cloud provider shut down our hosted instance for "compute engine  maintenance" 🫠 It is now back up. 
<img width="1007" alt="image" src="https://github.com/ShishirPatil/gorilla/assets/30296397/c01fe759-e969-4727-acdc-d305269ccef3">
