### ISSUE TITLE
[bug] Hosted Gorilla: <Issue>

### ISSUE THREAD

**Issue by Rudrapatel2812** [ShishirPatil/gorilla#451]
Exception: Error communicating with OpenAI: HTTPConnectionPool(host='zanino.millennium.berkeley.edu', port=8000): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x788e1aefa020>: Failed to establish a new connection: [Errno 111] Connection refused'))
Failed model: gorilla-7b-hf-v1, for prompt: take a youtube and generate blog based on the content of the youtube video

**Comment by ShishirPatil** [comment]
Thanks for raising this. Acknowledge and I am looking into it.

**Comment by ShishirPatil** [comment]
The campus (UC Berkeley) lost power which led to this, this should now be fixed.
