### ISSUE TITLE
[bug] Hosted Gorilla: <Issue>

### ISSUE THREAD

**Issue by AdityaPrasad275** [ShishirPatil/gorilla#454]
Exception: Error communicating with OpenAI: HTTPConnectionPool(host='zanino.millennium.berkeley.edu', port=8000): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ad587212b30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Failed model: gorilla-7b-hf-v1, for prompt: I would like to see a astronaut riding on a horse on moon with indian flag in hand

**Comment by ShishirPatil** [comment]
Thanks for raising @AdityaPrasad275 The campus (UC Berkeley) lost power which led to this, this should now be fixed.
