### ISSUE TITLE
[bug] Hosted Gorilla: <Issue>

### ISSUE THREAD

**Issue by AdityaPrasad275** [ShishirPatil/gorilla#455]
Exception: HTTP code 502 from API (<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>
)
Failed model: gorilla-7b-hf-v1, for prompt: I would like to see a astronaut riding on a horse on moon with indian flag in hand

**Comment by AdityaPrasad275** [comment]
This was the alternate mirror api endpoint

**Comment by ShishirPatil** [comment]
Thanks for raising @AdityaPrasad275  The campus (UC Berkeley) lost power which led to this, this should now be fixed.
