### ISSUE TITLE
How to generate training samples by self-Instruct

### ISSUE THREAD

**Issue by cquliujian** [ShishirPatil/gorilla#46]
Thank you very much for your work！

In this repository,  I see API data and training data, what prompt should I use to generate training data from API data.

Thanks！

**Comment by cquliujian** [comment]
"<<<code>>>" in train data also generated by self-Instruct？

**Comment by FanWan** [comment]
> "code " in train data also generated by self-Instruct？
"code " in train data  includes ''Instructio" and "Output" which can be constructed as  Instruction-API pair ?

**Comment by FanWan** [comment]
> "code " in train data also generated by self-Instruct？

"code " in train data includes ''Instructio" and "Output" which can be constructed as Instruction-API pair ?

**Comment by FanWan** [comment]
> "code " in train data also generated by self-Instruct？

"code " in train data includes ''Instruction" and "Output" which can be constructed as Instruction-API pair ?

**Comment by Jeffwan** [comment]
self-instruct code is definitely not open sourced yet.

**Comment by bitnom** [comment]
> self-instruct code is definitely not open sourced yet. You can send me email and we can discuss some details if you are interested in. @cquliujian @FanWan

This using retrieval and AST is really cool.

**Comment by TomExMachina** [comment]
> self-instruct code is definitely not open sourced yet. You can send me email and we can discuss some details if you are interested in. @cquliujian @FanWan

This using AST and retrieval is really cool.
