### ISSUE TITLE
[bug] OpenFunctions-v2: <HTTP code 502>

### ISSUE THREAD

**Issue by philuxzhu** [ShishirPatil/gorilla#467]
**Describe the bug**
The example code to invoke the hosted Gorilla Openfunctions-v2 model shows HTTP code 502. Anybody knows what’s the problem？

The example code:

def get_gorilla_response(prompt="", model="gorilla-openfunctions-v2", functions=[]):
    openai.api_key = "EMPTY"  # Hosted for free with ❤️ from UC Berkeley
    openai.api_base = "http://luigi.millennium.berkeley.edu:8000/v1"
    try:
        completion = openai.ChatCompletion.create(
            model="gorilla-openfunctions-v2",
            temperature=0.0,
            messages=[{"role": "user", "content": prompt}],
            functions=functions,
        )
        # completion.choices[0].message.content, string format of the function call
        # completion.choices[0].message.functions, Json format of the function call
        return completion.choices[0]
    except Exception as e:
        print(e, model, prompt)

**Screenshots**
<img width="990" alt="image" src="https://github.com/ShishirPatil/gorilla/assets/12409034/bafa7cc0-a0fb-4184-a4a6-0e75f7de5bd3">

**Comment by ShishirPatil** [comment]
Hey @philuxzhu the model was down then. This should now be fixed? I was able to run this without any issues. Please feel to re-open if you run into any issues!
