### ISSUE TITLE
What's the GPTIndex, Oracle retriever in the paper? 

### ISSUE THREAD

**Issue by Jeffwan** [ShishirPatil/gorilla#48]
1. Could you help share the reference of the oracle retriever? I can not find it from the paper.

2.  Is the GPTIndex in the paper LLamaIndex? I know GPTIndex has been rename to LLamaIndex https://github.com/jerryjliu/llama_index and just like to confirm that. If so, what's the index method you are using? List? Tree or something else?

**Comment by tianjunz** [comment]
1. The Oracle retriever uses the instruction-answer pair we generated from the dataset. Here is an example: https://github.com/ShishirPatil/gorilla/blob/main/data/apibench/huggingface_eval.json, and we just use the dataset as a retriever.
2. We just use GPT to embed all the files and take the nearest neighbor, it is simply a list.
