### ISSUE TITLE
[BFCL] Sanity check should be optional and by default off

### ISSUE THREAD

**Issue by ShishirPatil** [ShishirPatil/gorilla#486]
For BFCL eval, the sanity check of weather all RESTful APIs are active should be optional flag that is `off` by default. It is currently `on` by default.

**Comment by HuanzhiMao** [comment]
I think it should be `off` by default. We want to warn the users as soon as possible if the API is down, because that will make the result inaccurate. The user can then choose to ignore the warning and proceed with the evaluation if they want.

**Comment by ShishirPatil** [comment]
So, if a single RESTful API is down, rite now we just exit the evaluation - even offline AST based evals are not run although AST based evals are independent and not-affected by the online RESTful APIs. What we should do is that if a set of online RESTful APIs are down (e.g. Yahoo Finance) we should flag it to the user so they know exactly what the error bounds are, and then we should continue execution.
