### ISSUE TITLE
Questions on evaluation data in the project and paper

### ISSUE THREAD

**Issue by Jeffwan** [ShishirPatil/gorilla#49]
1.  Could I know what does `FT` and `RT` mean here? finetuning? 
![image](https://github.com/ShishirPatil/gorilla/assets/4739316/b2a84688-58d7-4614-bfb7-73ccd13168ad)

2. I notice it's hard for LLM to always generate right formats. Here's are some examples. How did you handle these kind of responses. Did you exclude them when you build the charts from the paper? Do you generate percentage of the invalid records? 

https://github.com/ShishirPatil/gorilla/blob/main/eval/eval-data/responses/huggingface/response_huggingface_Gorilla_FT_0_shot.jsonl
![image](https://github.com/ShishirPatil/gorilla/assets/4739316/56e08e0b-a54f-4779-9eba-86c7d73ce9f7)

**Comment by FanWan** [comment]
I'm also very interested in about it. Wait for reply!!!
