### ISSUE TITLE
Java/Javascript Scores

### ISSUE THREAD

**Issue by GeniusYx** [ShishirPatil/gorilla#495]
Hi~:

Can we show the detailed scores for Java/Javascript splits on the leaderboard (instead of the averaged AST Simple function)? 

Thanks！

**Comment by ShishirPatil** [comment]
Hey @GeniusYx thanks for your feedback. All the scores (including Java/JS) are [here](https://github.com/ShishirPatil/gorilla/blob/gh-pages/data.csv). We show aggregates on the leaderboard so as to not confuse folks or make it intractable to parse.
