### ISSUE TITLE
[Apibench] No module named 'tree_sitter_java'

### ISSUE THREAD

**Issue by XuHwang** [ShishirPatil/gorilla#514]
**Describe the issue**
I have installed packages according to the [doc](https://github.com/ShishirPatil/gorilla/tree/main/berkeley-function-call-leaderboard). But when I run `python openfunctions_evaluation.py`, it failed with `ModuleNotFoundError: No module named 'tree_sitter_java'` in `berkeley-function-call-leaderboard/model_handler/java_parser.py, line 3`. 

I tried to install the package `pip install tree-sitter-java`, which installed the version `0.21.0`. But the evaluation still failed with an error `TypeError: expected str, bytes or os.PathLike object, not int` in `berkeley-function-call-leaderboard/model_handler/java_parser.py line 7`, where the output of `tree_sitter_java.language()` is a strange number `140316658393504`.

I want to know how to install the packages correctly, thanks~

**Comment by HuanzhiMao** [comment]
Hi @XuHwang,
Could you try to re-install everything with the version specified in #515? Let me know if it works for you.

**Comment by XuHwang** [comment]
Thanks for the solution! It works for me~
