### ISSUE TITLE
Evaluation using vLLM and other tools

### ISSUE THREAD

**Issue by nightwatcher-of-abyss** [ShishirPatil/gorilla#518]
I adjusted get_llm_responses.py and did not use 'wandb', and my llm can actually receive request and prompts, but two empty directories named with 'xxxxwandb_artifact' and 'xxxxxwandb_media' instead of my output file.

**Comment by ShishirPatil** [comment]
hey @nightwatcher-of-abyss without the "adjustment" it is hard to tell? Also, hopefully this didn't come in the way of LLM generation? I'd like to think of WandB as a quality of life improvement and so not critical ? Let me know if you feel we should prioritize it!
