### ISSUE TITLE
Test data error in executable parallel multiple function

### ISSUE THREAD

**Issue by lucenzhong** [ShishirPatil/gorilla#519]
I think there may be some issue with the test data. 
Line 21 in `gorilla_openfunctions_v1_test_executable_parallel_multiple_function.json`

**Question**
```
{"question": "As a math enthusiast, John has set himself a new challenge. He's interested in the Fibonacci sequence and, more specifically, wants to work with the 5th and 8th numbers in the sequence. His plan is to calculate the greatest common divisor of these two Fibonacci numbers. Additionally, he's curious about something a bit more spatial \u2013 he wants to know the distance between the points (3, 4) and (8, 10) on a 2D plane. Could you assist in determining the GCD of those Fibonacci numbers and the distance between the points?"}
```
**Ground Truth**
```
["get_fibonacci_sequence(n=10)", "math_gcd(a=5, b=8)", "get_distance(pointA=(3, 4), pointB=(8, 10))"]
```

1. I think the parameter `n` for the get_fibonacci_sequence function can be any number greater than or equal to 8.
2. The 5th and 8th numbers are 3 and 13, respectively. I think this query needs sequential call rather than parallel call.

**Comment by HuanzhiMao** [comment]
Good catch. Thanks for flagging this @lucenzhong !
