### ISSUE TITLE
Gorilla Self-Hosted

### ISSUE THREAD

**Issue by SwenVogel** [ShishirPatil/gorilla#52]
Hi,

is it also possible to self host Gorilla with an API that is compatible with the OpenAI chat completion API?
So essentially the same as depicted in the Colab?

**Comment by chenhunghan** [comment]
You can use my project https://github.com/chenhunghan/ialacol to host https://huggingface.co/TheBloke/gorilla-7B-GGML

**Comment by ShishirPatil** [comment]
Hey @chenhunghan great tool! I just tried and it works well :) Do you maybe want to come up with a simple README tutorial for hosting Gorilla and using the Gorilla ggml? I'm happy to merge it and also announce it on Discord.

**Comment by ShishirPatil** [comment]
Awesome @chenhunghan ! Let me know if you run into any issues or need any help. Looking forward to it 🚀

**Comment by ShishirPatil** [comment]
Hey @chenhunghan just wanted to check on the status of this! If you do find the time, would love to welcome your contribution!
