### ISSUE TITLE
wrong datapoint field in formatter for data generation

### ISSUE THREAD

**Issue by HuiyingLi** [ShishirPatil/gorilla#534]
Hi, 
I am trying to generate synthetic data using my own pdf files, and want my output data to be "completion" format. 
In raft.py: https://github.com/ShishirPatil/gorilla/blob/a9dd43559fdc523d0d731e8c5b1275bfba500dd9/raft/raft.py#L239
the `question` field only contains question, and no context.
In format.py: https://github.com/ShishirPatil/gorilla/blob/a9dd43559fdc523d0d731e8c5b1275bfba500dd9/raft/format.py#L107
the `question` field is taken as input. I think the context is missing here. Do you mean taking the `instruction` field where context is appended by question? 
I'd appreciate it if you could clarify. 
Thanks!

**Comment by CharlieJCJ** [comment]
Hi @HuiyingLi, thanks for raising. Yes, this was a mistake in the original codebase, this was raised sometime ago but never got changed...

It should be `newds = ds.rename_columns({'instruction': 'prompt', 'cot_answer': 'completion'}) `

The "instruction" field already has a question appended. 

```python
context = ""
        for doc in docs:
            context += "<DOCUMENT>" + str(doc) + "</DOCUMENT>\n"
        context += q
```

We're refactoring the codebase and will fix it soon in both the current version and the new version.

**Comment by HuiyingLi** [comment]
@CharlieJCJ  Thank you so much for your prompt clarification!

**Comment by HuanzhiMao** [comment]
To clarify, we are only refactoring the codebase for the BFCL section. The RAFT section would remain unchanged. I will push a patch for this datapoint field issue now.
