### ISSUE TITLE
load-8bit flag doesn't work

### ISSUE THREAD

**Issue by marimeireles** [ShishirPatil/gorilla#54]
**Describe the issue**
When I use the `--load-8bit` flag it's returning a `load_compress_model` that's not imported anywhere (and for that reason -I guess- it's failing?). 

Any ideas on how to go about this issue? I've searched for this obj in the code itself and in hugging face's API but couldn't find it, so I'm kind of clueless on what to do.

I'm running this on a one GPU machine. It's an old T420 with archlinux.

Thanks!

**Comment by ShishirPatil** [comment]
Thanks for raising this @marimeireles! I think we fixed this flag and will enable the functionality in #77
