### ISSUE TITLE
The provided response file test results are not consistent with the paper[bug] Hosted Gorilla: <Issue>

### ISSUE THREAD

**Issue by FanqingM** [ShishirPatil/gorilla#56]
**Describe the bug**

We use the file /eval/eval-data/responses/torchhub/response_torchhub_Gorilla_FT_0_shot.jsonl and then use the code /eval/eval-scripts/ast_eval_th.py to calculate the metrics The final calculated result is Final Functionality accuracy: 75.80 Final hallucination: 16.12, which is the same as the final Functionality accuracy of zero-shot of torchhub published in Table1 of the paper. 59.13 Final hallucination: 6.98 is a big difference

**To Reproduce**
1. We use the file /eval/eval-data/responses/torchhub/response_torchhub_Gorilla_FT_0_shot.jsonl and then use the code /eval/eval-scripts/ast_eval_th.py to calculate the metrics

**Screenshots**
None

**Proposed Solution**
None

**Additional context**
We would like to know why there is a large discrepancy with the original published results, whether it is because an update was made or we compared the wrong table.

**Comment by ShishirPatil** [comment]
Thanks for raising this @FanqingM I think this is similar to #17 

When we open-sourced Gorilla, we further cleaned up the data which reflects in the improved performance - the code/pipeline remains same. Our plan was to update the paper in the camera ready if it gets accepted, or in the subsequent submission 🤞

Feel free to reopen the issue if you have any follow-up questions!
