### ISSUE TITLE
[BFCL] Issue with temporal models/function calling

### ISSUE THREAD

**Issue by aw632** [ShishirPatil/gorilla#581]
New models like Llama 3.1 have the "Cutting Knowledge Date" and the current date built into the system prompt. With these, some of the test cases need to be updated.

Example: #183, `simple` has this parameter:
```
"year": {
            "type": "integer",
            "description": "The year in which the lawsuit case was initiated. Default is latest year if not specified.",
            "optional": true
          }
```

The current possible answers only allow for `""`, but if the model has the current date/"cutting knowledge date", the latest year could be a real year. Should we account for this in the test cases?

**Comment by HuanzhiMao** [comment]
Hi @aw632,
Good point. Thanks for pointing this out. We will address it.
