### ISSUE TITLE
[Apibench] How to evaluate a model by openai API?

### ISSUE THREAD

**Issue by djstrong** [ShishirPatil/gorilla#592]
I have remotely hosted vllm models. How to evaluate them?

**Comment by HuanzhiMao** [comment]
Hey @djstrong, just want to double-check, are you referring to the evaluation in Apibench or the Berkeley Function Calling Leaderboard (BFCL)?

**Comment by djstrong** [comment]
Sorry, I mean BFCL.

**Comment by HuanzhiMao** [comment]
Take a look at the instructions [here](https://github.com/ShishirPatil/gorilla/tree/main/berkeley-function-call-leaderboard#contributing). Let me know if you have more questions!
