### ISSUE TITLE
[feature] Add a code in raft to do everything locally, like creating dataset and fine-tuning

### ISSUE THREAD

**Issue by himanshushukla12** [ShishirPatil/gorilla#597]
**I saw the approach which is great, but please add the fully locally doable process.**

**Comment by himanshushukla12** [comment]
I just want that i should be able to run the command given below without openAI API Key.
```
python3 raft.py \
  --datapath PATH_TO_DATA \
  --output OUTPUT_PATH \
  --output-format hf \ # or completion or chat
  --distractors 3 \
  --p 1.0 \
  --doctype pdf \
  --chunk_size 512 \
  --questions 5 \
  --openai_key YOUR_OPENAI_KEY
```

**Comment by ShishirPatil** [comment]
Merged #605

**Comment by Se-Hun** [comment]
Hello, I wanna fine-tuning my model with raft approach. But i didn't find the script for training.
Are you guys not going to release the fine-tuning code?

**Comment by himanshushukla12** [comment]
@Se-Hun They finetuned it using Azure Could, If you want I can push the new code to do the training locally.

**Comment by Se-Hun** [comment]
Thank you for your answering.
Can you push the new code for training ? I wanna reproduce this approach and i need the official code.

**Comment by himanshushukla12** [comment]
> Thank you for your answering. Can you push the new code for training? I wanna reproduce this approach and i need the official code.

@Se-Hun you can checkout code for fine-tuning any model, it is same as what they did.
