### ISSUE TITLE
Incorrect Response. Can be augmented with own data?

### ISSUE THREAD

**Issue by Usaid-Bin-Rehan** [ShishirPatil/gorilla#60]
![image](https://github.com/ShishirPatil/gorilla/assets/87263596/5d5ade52-e88d-479c-958c-ae96a8c1ab88)

**Comment by ShishirPatil** [comment]
Hi @Usaid-Bin-Rehan Thank you for trying our colab!
1. The models we host on the colab, are for APIs that are supported in HF, TF, TH. 
<img width="1296" alt="image" src="https://github.com/ShishirPatil/gorilla/assets/30296397/03d7d7a8-0e14-4834-9fab-f3c5a07b517a">
2. Gorilla was designed to help the developer with the exact API response, and not in a chat-style interface, so while "bubble sort" would be in scope, it might not be that helpful in "explaining" it. 
Feel free to re-open the issue if you have other questions :)
