### ISSUE TITLE
[BFCL] ModuleNotFoundError after Restructuring in Commit 70d6722: Incorrect Import Paths

### ISSUE THREAD

**Issue by kobe0938** [ShishirPatil/gorilla#614]
**Describe the issue**
After updating to commit [70d6722](https://github.com/ShishirPatil/gorilla/commit/70d6722e2e78621802b2810a2ec2213d52e8d4bc), the LLM inference command for the evaluation dataset fails on gorilla model. Specifically, running the command:
`python openfunctions_evaluation.py --model gorilla-openfunctions-v2 --test-category multiple --num-threads 1
`
results in the following error:
`ModuleNotFoundError: No module named 'model_handler'`

The root cause appears to be the relocation of the model_handler and eval_checker folders into a new folder named bfcl during the specified commit, without updating the relevant import paths in the code.

**ID datapoint**
1. Datapoint / Model Handler permalink: https://github.com/ShishirPatil/gorilla/blob/main/berkeley-function-call-leaderboard/bfcl/model_handler/gorilla_handler.py
https://github.com/ShishirPatil/gorilla/blob/main/berkeley-function-call-leaderboard/bfcl/model_handler/oss_handler.py
2. Issue: Failure to locate the model_handler module due to incorrect import paths.
2. Gorilla repo commit #: [70d6722](https://github.com/ShishirPatil/gorilla/commit/70d6722e2e78621802b2810a2ec2213d52e8d4bc)

**What is the issue**
The error disrupts the use of the LLM inference functionality for evaluating datasets, preventing execution with the current module paths.
**Proposed Changes**
Update the import statements in the following files to reflect the new directory structure:

`oss_handler.py`
`Current: `from model_handler.constant import DEFAULT_SYSTEM_PROMPT`
Proposed: `from bfcl.model_handler.constant import DEFAULT_SYSTEM_PROMPT`
`gorilla_handler.py`
Current: `from model_handler.constant import DEFAULT_SYSTEM_PROMPT`
Proposed: `from bfcl.model_handler.constant import DEFAULT_SYSTEM_PROMPT`

**Additional context**
The changes above restore functionality to the LLM inference process by correcting the module paths affected by the restructuring in commit 70d6722. A pull request with these fixes will be submitted shortly to address the problem.

**Comment by HuanzhiMao** [comment]
Hi @kobe0938,
Thanks for the issue! Could you try #612? It should have been fixed there.
