### ISSUE TITLE
[BFCL] [v1] Potential parsing issue in resolve_ast_by_type

### ISSUE THREAD

**Issue by thoang3** [ShishirPatil/gorilla#632]
**Describe the issue**
I have been working on BFCLv1 (I haven't migrated to BFCLv2 yet, but I suspect that this issue might persist), and found out that there's potential `ast` parsing issue in `resolve_ast_by_type` that could affect the performance of all models, especially in the `Simple` category.

**ID datapoint**
1. Datapoint / Model Handler permalink: https://github.com/ShishirPatil/gorilla/blob/main/berkeley-function-call-leaderboard/bfcl/model_handler/utils.py#L293-L295

**What is the issue**
The highlighted parsing might not be thorough which leads to potential degradation of several models. For example, with my fix in the Proposed Changes section, the `Simple Function AST` metric for `Meta-Llama-3-8B-Instruct` increases by 17% absolute. 

An actual example of the issue when running BFCLv1 on `Meta-Llama-3-8B-Instruct` without the fix is provided below for illustration purpose. In this case, the `model_result_raw` is `"\n\n[calculate_triangle_area({'base': 10, 'height': 5})]"` which could have been nicely handled by the proposed fix, which leads to the desired outcome.

```
{"id": 1, "model_name": "Meta-Llama-3-8B-Instruct", "test_category": "simple", "valid": false, "error": ["Did not output in the specified format. Note: the model_result is wrapped in a string to ensure json serializability."], "error_type": "ast_decoder:decoder_wrong_output_format", "prompt": {"question": "Find the area of a triangle with a base of 10 units and height of 5 units.", "function": {"name": "calculate_triangle_area", "description": "Calculate the area of a triangle given its base and height.", "parameters": {"type": "dict", "properties": {"base": {"type": "integer", "description": "The base of the triangle."}, "height": {"type": "integer", "description": "The height of the triangle."}, "unit": {"type": "string", "description": "The unit of measure (defaults to 'units' if not specified)"}}, "required": ["base", "height"]}}}, "model_result_raw": "\n\n[calculate_triangle_area({'base': 10, 'height': 5})]", "model_result_decoded": "[\"calculate_triangle_area({'base': 10, 'height': 5})\"]", "possible_answer": {"calculate_triangle_area": {"base": [10], "height": [5], "unit": ["units", ""]}}}
```

With the same fix, I also observe consistent improvements for `Simple Function AST` on several other models including our own models, ranging from 8% to 23%. 

**Proposed Changes**

Update the highlighted part to:
```
    elif isinstance(value, ast.Call):
        if len(value.keywords)==0:
            output = ast.unparse(value)
            h, t = output.split("(")
            t = t.split(")")[0]
            t = ast.literal_eval(t)
            output = {h: t}
```

**Comment by HuanzhiMao** [comment]
Hi @thoang3,
Apologies for the delay in response. This is not a bug. When we query the Llama models, we mentioned explicitly in the system prompt that it should output in the format `[func_name1(params_name1=params_value1, params_name2=params_value2...), func_name2(params)]` (code [here](https://github.com/ShishirPatil/gorilla/blob/main/berkeley-function-call-leaderboard/bfcl/model_handler/constant.py#L7-L8)). What the model outputs is not in this format (we ignore any `\n`); the function parameter section is in wrong format `"\n\n[calculate_triangle_area({'base': 10, 'height': 5})]"`
