### ISSUE TITLE
[OpenFunction-v2] Gorilla API does not work (SSL: CERTIFICATE_VERIFY_FAILED, certificate expired error)

### ISSUE THREAD

**Issue by hydang99** [ShishirPatil/gorilla#668]
**Describe the issue**
I got the issue when trying to run gorilla v2 and it get the error as CERTIFICATE_VERIFY_FAILED, certificate expired error.

**ID datapoint**
1. Datapoint / Model Handler permalink: 
2. Issue: 
2. Gorilla repo commit #: 

**What is the issue**

**Proposed Changes**

{
 'previous_datapoint':[], 
 'updated_datapoint':[]
}

**Additional context**

**Comment by hydang99** [comment]
I just want to ask if any updates on the issue. The full error when doing the inference is 
 Error: HTTPSConnectionPool(host='luigi.millennium.berkeley.edu', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)')))

**Comment by HuanzhiMao** [comment]
Hi, sorry for the wait. We are still trying to fix the certificate issue :/

**Comment by abitrolly** [comment]
@HuanzhiMao I can help setting up automatic certificate renewal. WhatsApp +375 29 3204241, https://github.com/abitrolly.keys

Do you use Ansible or any other automation for these?

* luigi.millennium.berkeley.edu (seems self hosted)
* cli.gorilla-llm.com (seems to be in Google cloud)

**Comment by CostaliyA** [comment]
> I just want to ask if any updates on the issue. The full error when doing the inference is Error: HTTPSConnectionPool(host='luigi.millennium.berkeley.edu', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)')))

I encountered the same problem as you, did you solve it?

**Comment by abitrolly** [comment]
@CostaliyA disabling HTTPS may work https://github.com/gorilla-llm/gorilla-cli/issues/60#issuecomment-2125402761

**Comment by HuanzhiMao** [comment]
Hi, 
The certificate issue should have been fixed now for the luigi endpoint. Apologies for the long delay.

**Comment by abitrolly** [comment]
@HuanzhiMao so what was the remediation?

**Comment by hydang99** [comment]
I do not think it works, the new problem occurs as {"detail":"Method Not Allowed"}

**Comment by abitrolly** [comment]
@hydang99 if it is not certification expired error, then it needs another issue to track.

**Comment by HuanzhiMao** [comment]
> @HuanzhiMao I do not think it works, the new problem occurs as {"detail":"Method Not Allowed"}

 Could you elaborate how you get that error? The openfunction endpoint is working for me.

**Comment by hydang99** [comment]
I see, I got a mistake. It works for me now
