### ISSUE TITLE
[BFCL] Reproduction xLAM 1b-fc-r does not match for parallel and irelavance categories

### ISSUE THREAD

**Issue by gaspardob** [ShishirPatil/gorilla#699]
Hello,
First of all thank you very much for your work, it helps a lot.

While I have very good results when reproducing for xLAM 7b-r, Qwen 2.5, or ToolAce 8B, I obtain strange results with xLAM 1b-fc-r (and also with llama 3.2 1B and 3B Instruct)

Here are the poor results I obtained with them (I put xLAM 7b-r for comparaison). They are very different in the parallel categories from what you have on the leaderboard.
![resuluts_bfclv3_xlam](https://github.com/user-attachments/assets/6bc6c5e9-7027-4df2-9b81-e7ec44177ce1)

When I check the results, xLAM 1b-fc-r make only single calls, and never make parallel predictions. Is it normal ?
Moreover, results with the latest LLAMA 3.2 Instruct are also very poor. This is strange, what results do you have, is LLAMA 3.2 really compatible with vllm ? (I have personnaly no error when running).

Thank you

For information, I run the evaluation with
`python -m openfunctions_evaluation --model Salesforce/xLAM-1b-fc-r --test-category all --num-threads 1 && \
  python -m bfcl.eval_checker.eval_runner --model Salesforce/xLAM-1b-fc-r --test-category all`

**Comment by HuanzhiMao** [comment]
Hi @gaspardob,
The score you reported looks similar to the one in #672 (file link [here](https://github.com/ShishirPatil/gorilla/blob/9bbf36c792bb4be881af924db080a9722707c952/data_overall.csv)). The Llama3.2 scores are also included in that PR, which hasn't been merged yet.

**Comment by gaspardob** [comment]
Ok perfect, thank you for your answer @HuanzhiMao  !
And so you think that the evaluation of llama 3.2 is not really working at the moment ?

**Comment by HuanzhiMao** [comment]
The evaluation is working. You can run the pipeline locally to get a score. It's just we haven't updated their score to the leaderboard yet (due to some delay). The score you obtained locally should be the same as the one we will report on the leaderboard.

**Comment by gaspardob** [comment]
Ok thank you, I was wondering because results of the small llama models were bad, and the 3.2 8B instruct worse than 3.1 8B instruct.

**Comment by zuxin666** [comment]
Hi @gaspardob , thanks for catching this. We identified several implementation issues in the Salesforce model handler when assembling the prompt, which might cause the poor performance. We will send a PR to fix this issue later. The results from our side of evaluation for the 1b model is:

<img width="1502" alt="image" src="https://github.com/user-attachments/assets/b766dfd5-cea5-4a99-942f-c920d9fdb9c5">

It is able to produce parallel function calls.

**Comment by khongtrunght** [comment]
> Hello, First of all thank you very much for your work, it helps a lot.
> 
> While I have very good results when reproducing for xLAM 7b-r, Qwen 2.5, or ToolAce 8B, I obtain strange results with xLAM 1b-fc-r (and also with llama 3.2 1B and 3B Instruct)
> 
> Here are the poor results I obtained with them (I put xLAM 7b-r for comparaison). They are very different in the parallel categories from what you have on the leaderboard. ![resuluts_bfclv3_xlam](https://private-user-images.githubusercontent.com/144008529/376313414-6bc6c5e9-7027-4df2-9b81-e7ec44177ce1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwMDQwNTMsIm5iZiI6MTczMzAwMzc1MywicGF0aCI6Ii8xNDQwMDg1MjkvMzc2MzEzNDE0LTZiYzZjNWU5LTcwMjctNGRmMi05YjgxLWU3ZWM0NDE3N2NlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEzMFQyMTU1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmYxZDNlZTMxY2ZkYWZmY2ZhZmVhNjQ1NzM2YTE3NzczZTA0ZDM3MTU4OWE2ZTBiMzEwNWNlN2ZkYjk1MTEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.B6u84eFeUgTPQF1SVXXWcyRjFIA_vgfGInXSX4CZCfc)
> 
> When I check the results, xLAM 1b-fc-r make only single calls, and never make parallel predictions. Is it normal ? Moreover, results with the latest LLAMA 3.2 Instruct are also very poor. This is strange, what results do you have, is LLAMA 3.2 really compatible with vllm ? (I have personnaly no error when running).
> 
> Thank you
> 
> For information, I run the evaluation with `python -m openfunctions_evaluation --model Salesforce/xLAM-1b-fc-r --test-category all --num-threads 1 && \ python -m bfcl.eval_checker.eval_runner --model Salesforce/xLAM-1b-fc-r --test-category all`

Could you share with me the command you use to run this. I want to run benchmark for Salesforce/xLAM-7b-fc-r model on multi-turn test category. But all the responses say that the content length is exeede 4096 .

command : bfcl generate --model Salesforce/xLAM-7b-fc-r --test-category multi_turn --backend vllm --num-gpus 1 --gpu-memory-utilization 0.90
result something like : This model's maximum context length is 4096 tokens. However, you requested 8488 tokens in the messages, Please reduce the length of the messages.
