### ISSUE TITLE
[BFCL] I encountered a path problem when doing eval

### ISSUE THREAD

**Issue by CostaliyA** [ShishirPatil/gorilla#703]
Thank you for your outstanding work!! When I ran the eval_checker.py, I encountered an error message: 'from bfcl.constant import (ModuleNotFoundError: No module named 'bfcl''. This can be done by modifying the root directory of the file. 
`import argparse
import sys
import os
sys.path.append(r'/home/code/gorilla/berkeley-function-call-leaderboard')#Your Own Path`

**Comment by HuanzhiMao** [comment]
I think you might forget to `pip install -e.` first. https://github.com/ShishirPatil/gorilla/tree/main/berkeley-function-call-leaderboard#install-dependencies

**Comment by CostaliyA** [comment]
I have made sure that I have executed pip install -e. In addition, this problem only occurs in eval_checker.py and not in the inference stage. It may be a local problem of mine. Thank you for your answer.

**Comment by CostaliyA** [comment]
I have solved it. Thank you for your replies! My bad, I forgot to close this issue.
