### ISSUE TITLE
[BFCL] Writer’s Palmyra X 004

### ISSUE THREAD

**Issue by farawayxxx** [ShishirPatil/gorilla#705]
May I ask if there are any plans to test the effectiveness of the Writer’s Palmyra X 004? Its performance looks amazing.
<img width="855" alt="image" src="https://github.com/user-attachments/assets/d0e92421-830c-42ed-aeab-3ac48666adc8">

**Comment by HuanzhiMao** [comment]
As far as I know, the Writer people are working on a PR to add their models.
