### ISSUE TITLE
[bug] Hosted Gorilla: <Issue>

### ISSUE THREAD

**Issue by Science2AI-TaoXu** [ShishirPatil/gorilla#71]
Exception: Invalid response object from API: '{"object":"error","message":"","code":50001}' (HTTP response code was 400)
Failed model: gorilla-7b-hf-v1, for prompt: I would like to translate 'I feel very good today.' from English to Chinese

**Comment by surya-narayanan** [comment]
I'm also curious why this is happening?

**Comment by ShishirPatil** [comment]
Thanks for flagging this @Science2AI-TaoXu and @surya-narayanan. I was able to identify that this error was due to our GPUs memory getting corrupted. I will diagnose why this happened when I am back from ICML :)
