### ISSUE TITLE
[BFCL] How to Evaluate the Spark Giant Model:

### ISSUE THREAD

**Issue by lonelysheeep** [ShishirPatil/gorilla#726]
**Describe the issue**
How to evaluate large models, if the URL and API are known, which code needs to be modified, what code needs to be added, and what the logic should be like.
thanks

**Comment by HuanzhiMao** [comment]
Hi, Please take a look at this section: https://github.com/ShishirPatil/gorilla/tree/main/berkeley-function-call-leaderboard#contributing 
Let me know if you have more questions.
