### ISSUE TITLE
[BFCL]  I tested some oss model on the AST dataset offline using a local environment, and the scores differ significantly from the leaderboard. What points might I have overlooked? Here are the results of the experiment.

### ISSUE THREAD

**Issue by 17828079650** [ShishirPatil/gorilla#741]
![74ff92148e26f456d5b9be5d8d8af2f](https://github.com/user-attachments/assets/c40f1622-07a6-4224-a319-6c88afb7e0a5)

**Comment by HuanzhiMao** [comment]
Hi, 
Could you share the command you use to generate those results and the platform info (eg, GPU model, vllm/sglang version, etc)? Thanks!

**Comment by 17828079650** [comment]
Thank you very much for your reply.
I just used commands like this: 
bfcl generate --model ToolACE-8B--test-category ast--backend sglang --num-gpus 1 --gpu-memory-utilization 0.9
and this one to evaluate:
bfcl evaluate --model ToolACE-8B --test-category ast
all these commands are the same as the one mentioned in the readme.md without any other great changes. 
I am confused by the results

**Comment by HuanzhiMao** [comment]
I think you need to adjust the `max_token` value to a lower number (say 1024) when doing inference for these small OSS models. They tend to have small context windows, and using 4096 would results in a lot of content length exceeded error (which could be avoided if set to a lower value). 
Alternatively, you could incorporate #712, which automatically set the appropriate `max_token` value.

**Comment by 17828079650** [comment]
Thank you very much! It does work well!

**Comment by khongtrunght** [comment]
> Thank you very much! It does work well!

Could you share with me the command you use to run this. I want to run benchmark for Salesforce/xLAM-7b-fc-r model on multi-turn test category. But all the responses say that the content length is exeede 4096 .

command : `bfcl generate --model Salesforce/xLAM-7b-fc-r --test-category multi_turn --backend vllm --num-gpus 1 --gpu-memory-utilization 0.90`
result something like : `This model's maximum context length is 4096 tokens. However, you requested 8488 tokens in the messages, Please reduce the length of the messages.`
