### ISSUE TITLE
[BFCL] How to add our own llm into Leaderboard?

### ISSUE THREAD

**Issue by fengzhu1** [ShishirPatil/gorilla#757]
I am an engineer from Ant Group (China), and we are interested in adding a new language model to your Leaderboard. Could you please provide guidance on the process? Specifically, do you require a public API for the language model, or are there other methods for submission?

Thank you for your assistance.

**Comment by HuanzhiMao** [comment]
Please checkout this README. https://github.com/ShishirPatil/gorilla/tree/main/berkeley-function-call-leaderboard#contributing

**Comment by fengzhu1** [comment]
Thanks

**Comment by fengzhu1** [comment]
> Please checkout this README. https://github.com/ShishirPatil/gorilla/tree/main/berkeley-function-call-leaderboard#contributing

Hi Huanzhi，

Could you please inform us about the update frequency of the Berkeley Function Calling Leaderboard? Specifically, how soon after submitting a pull request with our new Model Handler can we expect to see the updated leaderboard?
