### ISSUE TITLE
[feature] Run gorilla locally without GPUs 🦍

### ISSUE THREAD

**Issue by ShishirPatil** [ShishirPatil/gorilla#77]
Today, Gorilla end-points run on UC Berkeley hosted servers 🐻  When you try our colab, or our chat completion API, or the CLI tool, it hits our GPUs for inference. A popular ask among our users is to run Gorilla locally on Macbooks/Linux/WSL. 

**Describe the solution you'd like:**
Have the model(s) running locally on MPS/CPU/GPU and listening to a port. All the current gorilla end-points can then just hit `localhost` to get the response to any given prompt. 

**Additional context:**
Here is an application that would immediately use it: https://github.com/gorilla-llm/gorilla-cli
Given, we have LLaMA models, these should be plug-and-play: [ggerganov/llama.cpp](https://github.com/ggerganov/llama.cpp) and [karpathy/llama2.c](https://github.com/karpathy/llama2.c)
Also relevant: https://huggingface.co/TheBloke/gorilla-7B-GPTQ

Update 1: If you happen to have an RTX, or V100 or A100 or H100, you can use Gorilla today without any latency hit. The goal of this enhancement is to help those who may not have access to and greatest GPUs.

**Comment by fire** [comment]
I am excited about a possible integration using ggml and mpt. 

https://github.com/ggerganov/ggml/tree/master/examples/mpt

How much code is specific to gorilla that needs to port from python to c++?

How much code is in the llm?

**Comment by ShishirPatil** [comment]
Hey @fire for the first cut, we don't have to use any gorilla specific code nor any finetuning. It would just be inference - and there is no change in the architecture of either llama or MPT, so the port should be pretty straightforward. The model weights are here https://huggingface.co/gorilla-llm

**Comment by fire** [comment]
As of today which model should I be using?

**Comment by fire** [comment]
Can someone help me quantize?

```
# get the repo and build it
git clone https://github.com/ggerganov/ggml
cd ggml
mkdir build && cd build
cmake ..
make -j

# get the model from HuggingFace
# be sure to have git-lfs installed
git clone https://huggingface.co/gorilla-llm/gorilla-mpt-7b-hf-v0

# convert model to FP16
python3 ../examples/mpt/convert-h5-to-ggml.py ./gorilla-mpt-7b-hf-v0 1

# run inference using FP16 precision
./bin/mpt -m ./mpt-30b/ggml-model-f16.bin -p "I believe the meaning of life is" -t 8 -n 64

# quantize the model to 5-bits using Q5_0 quantization
./bin/mpt-quantize ./mpt-30b/ggml-model-f16.bin ./mpt-30b/ggml-model-q5_0.bin q5_0
```

**Comment by fire** [comment]
I was expecting to be put next to https://huggingface.co/gorilla-llm but with a ggml tag and the tag q5 I think.

I've also written up instructions for llama

# gorilla-llm/gorilla-7b-hf-delta-v1

```
# get the repo and build it
git clone https://github.com/ggerganov/llama.cpp
cd llama.cpp
mkdir build && cd build
cmake ..
make -j

# get the model from HuggingFace
# be sure to have git-lfs installed
git clone https://huggingface.co/gorilla-llm/gorilla-7b-hf-delta-v1

# convert model to FP16
python3 convert.py ~/gorilla-7b-hf-delta-v1

# run inference using FP16 precision
./bin/main -m ./gorilla-7b-hf-delta-v1/ggml-model-f16.bin -p "I would like to translate 'I feel very good today.' from English to Chinese." -t 8 -n 64

# quantize the model to 5-bits using Q5_0 quantization
./bin/quantize ./gorilla-7b-hf-delta-v1/ggml-model-f16.bin ./gorilla-7b-hf-delta-v1/ggml-model-q5_0.bin q5_0

# run inference using FP16 precision
./bin/main -m ./gorilla-7b-hf-delta-v1/ggml-model-q5_0.bin -p "I would like to translate 'I feel very good today.' from English to Chinese." -t 8 -n 64
```

Llama evaluates poorly. No idea why.

**Comment by ShishirPatil** [comment]
@fire we have the mpt-ggml and the llama--ggml models up on Huggingface! 
[gorilla-llm/gorilla-7b-hf-v1-ggml](https://huggingface.co/gorilla-llm/gorilla-7b-hf-v1-ggml)
[gorilla-llm/gorilla-mpt-7b-hf-v0-ggml](https://huggingface.co/gorilla-llm/gorilla-mpt-7b-hf-v0-ggml)

**Comment by fire** [comment]
The links are 404'ing not found.

**Comment by ShishirPatil** [comment]
Yikes, I think they were private! Made it public. Let me know if it works! Also, feel free to raise a PR for updates to README or anything you want to put into the HF models repo!

**Comment by dbian** [comment]
Would you open source the "chat completion API" server code? I can not find it in this repository. Thanks.

**Comment by CHIRU98** [comment]
Hi ShishirPatil still this is "gorilla-llm/gorilla-7b-hf-v1-ggml" is private.can you check ones.still its getting the 401 Client Error.

**Comment by pranramesh** [comment]
@ShishirPatil Is the quantized llama based model at (https://huggingface.co/gorilla-llm/gorilla-7b-hf-v1-ggml) after combining the delta weights with base llama? I'm wondering because inference with the quantized model created from the llama-based script that @fire provided is poor. I suspect this is due to the delta weights model being quantized with inference being run on that rather than the correct model.

**Comment by pranramesh** [comment]
@ShishirPatil I believe the quantized llama model here (https://huggingface.co/gorilla-llm/gorilla-7b-hf-v1-ggml) is a quantized version of the delta weights model. I tried running inference and it was poor, probably due to the fact that it wasn't merged with llama first.
