### ISSUE TITLE
[BFCL] Error when consecutively generate from multiple oss_models with vllm

### ISSUE THREAD

**Issue by YifanHao** [ShishirPatil/gorilla#774]
I have plenty of models and I want to test them all. So I run a bash script like this:
```
bfcl generate --model "model_1" --test-category simple
bfcl generate --model "model_2" --test-category simple
...
```
The first generation was good. But the second run and thereafter encountered the following error:
![image](https://github.com/user-attachments/assets/cb93bb9f-a4b6-4be9-99d5-889d5835577a)
I suspect the reason is that VLLM_PORT still occupied by the previous run, so I got the output of `ps -aux` when the second run just began. However it seems the previous vllm server has already ended. 
![image](https://github.com/user-attachments/assets/3c68226c-f541-4f03-8c52-ec8a9268314e)

Now I have no idea why this isn't working, could you help me with this?
Or what's the recommended way if I want to run many models automatically?

Update: 
Just after I open this issue, I find the error disappears if I wait long enough before the next run. (`sleep 60` after each line). 
But still, I wonder if there's a better way to do this?

**Comment by HuanzhiMao** [comment]
Hi @YifanHao,
I think the issue you are encountering is because vllm takes some time to shutdown the server and clean up after all the inference are done, and so the best approach would be probably like what you are doing (eg, add some time interval between the runs).

**Comment by YifanHao** [comment]
Got it. Thanks for your reply!
