### ISSUE TITLE
Augmenting additional API to the Gorilla-LLm

### ISSUE THREAD

**Issue by mahdiAkhi** [ShishirPatil/gorilla#78]
I hope you are doing well, a great thanks for this work.
Is it possible to add additional APIs(private APIs) to Gorilla? We have a large database of APIs and we need to add them to Gorilla, How can we do this? Should we fine-tune the Gorilla LLM? or something like this?

**Comment by ShishirPatil** [comment]
Hey @mahdiAkhi thank you! Yes, indeed - we have an APIZoo where you can add your APIs to Gorilla. We will periodically train the model making it easy for you to use! Of course, you can also choose to train yourself :) 
Here's how you can contribute APIs:  https://github.com/ShishirPatil/gorilla/tree/main/data#how-to-contribute

Hope this helps! Feel free to re-open the issue if you have any more questions!
