### ISSUE TITLE
[bug] OpenFunctions-v2: <Issue>CUDA_VISIBLE_DEVICES=1 bfcl evaluate --model Qwen/Qwen2.5-7B-Instruct --test-category simple 执行这条命令，score目录生成的指标文件没有具体的数据。

### ISSUE THREAD

**Issue by gaochunrong** [ShishirPatil/gorilla#784]
执行CUDA_VISIBLE_DEVICES=1 bfcl evaluate --model Qwen/Qwen2.5-7B-Instruct --test-category simple 命令，目录：/bfcl/gorilla/berkeley-function-call-leaderboard/score/  下的data_overall.csv里面没有详细的指标数据，请问这是啥原因造成的？谢谢！

**Comment by HuanzhiMao** [comment]
You need to run `bfcl generate xxx` to obtain the model result first, before running the evaluation command.

**Comment by gaochunrong** [comment]
我现在是将模型下载到本地电脑上，路径是：/data/models/Qwen2___5-7B-Instruct，
 分别执行命令：bfcl generate --model /data/models/Qwen2___5-7B-Instruct --test-category simple --backend vllm   --num-gpus 1 --gpu-memory-utilization 0.9  这条命令有输出文件：BFCL_v3_simple_result.json
 
 bfcl evaluate --model /data/models/Qwen2___5-7B-Instruct --test-category simple
 这条命令报错：KeyError: '/data/models/Qwen2///5-7B-Instruct'  这是啥回事？

**Comment by HuanzhiMao** [comment]
需要加到这个mapping里面
https://github.com/ShishirPatil/gorilla/blob/main/berkeley-function-call-leaderboard/bfcl/eval_checker/model_metadata.py#L3

**Comment by gaochunrong** [comment]
己添加，输出如下内容:
Number of models evaluated: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 60349.70it/s]📈 Aggregating data to generate leaderboard score table...
🏁 Evaluation completed. See /data/gcr/bfcl/gorilla/berkeley-function-call-leaderboard/score/data_overall.csv for overall evaluation results on BFCL V3.
See /data/gcr/bfcl/gorilla/berkeley-function-call-leaderboard/score/data_live.csv, /data/gcr/bfcl/gorilla/berkeley-function-call-leaderboard/score/data_non_live.csv and /data/gcr/bfcl/gorilla/berkeley-function-call-leaderboard/score/data_multi_turn.csv for detailed evaluation results on each sub-section categories respectively.

现在的问题是带.csv后缀的文件里面没有具体的指标数据，请问这是啥回事？
![image](https://github.com/user-attachments/assets/33f01e98-6a97-4be3-9dc8-e3b9bf934659)

**Comment by HuanzhiMao** [comment]
score那个文件夹下有东西吗

**Comment by gaochunrong** [comment]
score目录下有data_live.csv，data_non_live.csv，data_multi_turn.csv，data_overall.csv这四个文件，没有BFCL_v3_simple_score.json

**Comment by gaochunrong** [comment]
BFCL_v3_simple_result.json 这个文件在另外一个文件夹result下

**Comment by HuanzhiMao** [comment]
我看你最一开始是用的 `--model Qwen/Qwen2.5-7B-Instruct`，为啥后来要换成`--model /data/models/Qwen2___5-7B-Instruct`

**Comment by gaochunrong** [comment]
我本地电脑的模型是从huggingface下载来的，存入在/data/models/Qwen2___5-7B-Instruct目录下，想直接加载就行了，不想再下载

**Comment by gaochunrong** [comment]
请问这个是啥回事？

**Comment by HuanzhiMao** [comment]
> 我本地电脑的模型是从huggingface下载来的，存入在/data/models/Qwen2___5-7B-Instruct目录下，想直接加载就行了，不想再下载

你应该改huggingface那边的路径。`--model`这个argument不管你本地存储的路径

**Comment by gaochunrong** [comment]
"Qwen/Qwen2.5-7B-Instruct": [
        "Qwen2.5-7B-Instruct (Prompt)",
        "/data/models/Qwen2___5-7B-Instruct",
        "Qwen",
        "apache-2.0",
    ], 
bfcl evaluate --model Qwen/Qwen2.5-7B-Instruct --test-category simple

**Comment by gaochunrong** [comment]
"Qwen/Qwen2-7B-Instruct": [
        "Qwen2-7B-Instruct (Prompt)",
        "export HF_HOME=/data/models/Qwen2___5-7B-Instruct",
        "Qwen",
        "apache-2.0",
    ], 是修改为这样的吗？

**Comment by HuanzhiMao** [comment]
不是，`export HF_HOME=xxx`是输在terminal里的...
用`--model Qwen/Qwen2.5-7B-Instruct`，然后model_metadata那边你应该是不用改的

**Comment by gaochunrong** [comment]
export HF_HOME=/data/models/Qwen2___5-7B-Instruct  输在terminal ？

**Comment by HuanzhiMao** [comment]
terminal里应该输的是`export HF_HOME=/data/models`

**Comment by gaochunrong** [comment]
(BFCL) gcr@ubuntu0:~/bfcl$ export HF_HOME=/data/gcr/models
(BFCL) gcr@ubuntu0:~/bfcl$ echo $HF_HOME
/data/gcr/models
(BFCL) gcr@ubuntu0:~/bfcl$ CUDA_VISIBLE_DEVICES=1 bfcl generate --model gorilla-openfunctions-v2 --test-category simple --backend vllm   --num-gpus 1 --gpu-memory-utilization 0.9
Generating results for ['gorilla-openfunctions-v2'] on test category: ['simple'].
Generating results for gorilla-openfunctions-v2:   0%|                                                                                                                        | 0/156 [00:00<?, ?it/s]----------------------------------------------------------------------------------------------------
❗️❗️ Error occurred during inference. Maximum reties reached for rate limit or other error. Continuing to next test case.
❗️❗️ Test case ID: simple_244, Error: HTTPSConnectionPool(host='luigi.millennium.berkeley.edu', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)')))
----------------------------------------------------------------------------------------------------
Generating results for gorilla-openfunctions-v2:   1%|▋                                                                                                               | 1/156 [00:01<03:08,  1.22s/it]----------------------------------------------------------------------------------------------------
❗️❗️ Error occurred during inference. Maximum reties reached for rate limit or other error. Continuing to next test case.
❗️❗️ Test case ID: simple_245, Error: HTTPSConnectionPool(host='luigi.millennium.berkeley.edu', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)')))
---------------------------------------------------------------------------------------------------- 

请问以上这个报错，如何处理？

**Comment by gaochunrong** [comment]
gorilla-openfunctions-v2 这个模型我己经下载好在/data/gcr/models里面了

**Comment by HuanzhiMao** [comment]
这个目前没法解决。gorilla-openfunctions-v2的hosted API endpoint最近有点问题；如果要换成local inference的话需要写新的model handler。可以考虑换个模型

**Comment by gaochunrong** [comment]
我现在想评估eval一下gorilla-openfunctions-v2这个模型的指标，看输出结果是啥样的?

**Comment by gaochunrong** [comment]
请问有好的解决方案吗？

**Comment by HuanzhiMao** [comment]
我可以发给你我们在 #748 里面跑出来的gorilla-openfunctions-v2的输出结果(不是最新的commit)。如果你想在你那边自己跑的话，现在解决不了(API掉线了)

**Comment by HuanzhiMao** [comment]
`HTTPSConnectionPool(host='cdn-lfs-us-1.hf-mirror.com', port=443): Read timed out.` 这个说的是你网络的问题吧？

**Comment by gaochunrong** [comment]
嗯嗯，现在执行输出结果如下：
### **核心指标分析**

#### 1. **Overall Accuracy（总准确率）**
   - **值**：1.18%
   - **分析**：总准确率非常低，表明模型在整体任务上的性能表现不佳。这可能反映出：
     - 数据集任务的难度较高。
     - 模型生成的回答在大多数情况下不能准确匹配目标答案。

#### 2. **模型信息**
   - **模型名称**：Qwen2.5-7B-Instruct (Prompt)
   - **模型链接**：[HuggingFace 模型链接](https://huggingface.co/Qwen/Qwen2.5-7B-Instruct)
   - **开源许可**：Apache-2.0
   - **组织**：Qwen
   
   **分析**：
   - 模型是一个开源的 7B 参数规模的指令调优语言模型。
   - 低准确率可能与任务或训练数据匹配度有关。

---

### **性能指标**

#### 3. **延迟（Latency）**
   - 平均延迟：6.55秒
   - 标准差：3.23秒
   - 95% 百分位延迟：12.51秒

   **分析**：
   - 平均延迟为 6.55 秒，且 95% 百分位达到了 12.51 秒，说明在部分请求上延迟非常高。
   - 任务复杂性或计算资源不足可能导致较高的延迟。

---

### **详细准确率分析**

#### **非实时 AST（Non-Live AST Accuracy）**
   - 总体准确率：7.98%
   - 简单任务准确率：31.92%
   - 复杂任务准确率：0%

   **分析**：
   - 简单任务的准确率较高，表明模型在处理简单问题时有一定能力。
   - 对于复杂任务（如多轮、多线程或并行任务），模型表现完全失败。

#### **执行准确率（Non-Live Exec Accuracy）**
   - **所有指标为 0%**
   
   **分析**：
   - 模型未能正确执行任务，可能与执行功能定义或外部依赖相关。

---

#### **实时任务（Live Accuracy）**
   - **所有指标为 0%**

   **分析**：
   - 实时任务的评估结果表明模型在动态上下文中的能力表现不佳。

---

#### **多轮对话任务（Multi Turn Accuracy）**
   - 总体准确率：0%
   - 子指标（Base, Miss Func, Miss Param, Long Context）：**全为 0%**
   
   **分析**：
   - 模型在多轮对话中无法正确预测函数调用，参数理解和上下文处理能力也完全缺乏。

---

#### **相关性检测**
   - **相关性检测（Relevance Detection）**：0%
   - **非相关性检测（Irrelevance Detection）**：0%

   **分析**：
   - 模型在判断任务相关性和无关性的能力上也完全失败。

---

### **问题总结**
1. **准确率极低**：
   - 总准确率仅 1.18%，且多个子任务准确率为 0%，说明模型性能不足。
   
2. **高延迟**：
   - 延迟较高且波动较大，可能受限于模型的计算需求和优化不足。
   
3. **实时任务和多轮任务表现差**：
   - 模型无法适应复杂、多轮对话任务或实时任务。
   
4. **相关性判断缺失**：
   - 模型对任务的语义相关性和上下文相关性没有足够的理解能力。

请问以上的指标数据为啥这么低？
