### ISSUE TITLE
[BFCL] The update frequency of the Berkeley Function Calling Leaderboard

### ISSUE THREAD

**Issue by fengzhu1** [ShishirPatil/gorilla#785]
Could you please inform us about the update frequency of the Berkeley Function Calling Leaderboard? Specifically, how soon after submitting a pull request with our new Model Handler can we expect to see the updated leaderboard?

**Comment by HuanzhiMao** [comment]
Hi @fengzhu1 , we will try to update the leaderboard as soon as possible, usually within a few days of the PR merge.
