### ISSUE TITLE
对于 API 托管Openai gpt4o模型生成和评估报错问题

### ISSUE THREAD

**Issue by gaochunrong** [ShishirPatil/gorilla#792]
目前用了openai gpt4o 的api key是正确的，用命令bfcl generate --model gpt-4o-2024-08-06-FC --test-category parallel --num-threads 1 报错如下;
{"id": "parallel_9", "result": "Error during inference: Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-l2PGB***************************************iY7Z. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}"}
请问是啥原因？

**Comment by HuanzhiMao** [comment]
这是你API key的问题，报错信息里已经说了 `Incorrect API key provided`
