### ISSUE TITLE
[BFCL] 自己微调训练的模型如何本地部署接入BFCL进行模型评估测试

### ISSUE THREAD

**Issue by belief888** [ShishirPatil/gorilla#794]
现有有一个问题是我这边自己用qwen2.5-7b微调的模型，要在本地GPU电脑接入BFCL进行模型评估测试，比如我微调之后模型的名称是：new_model2,请问这个模型需要如何处理？才可以在本地进行BFCL模型评估测试？

**Comment by belief888** [comment]
看过了，问题是new_model2这个本地模型路径是怎么从本地电脑加载过来的？分析过代码了，似是没有这方面的处理吗？

**Comment by HuanzhiMao** [comment]
[这几行](https://github.com/ShishirPatil/gorilla/blob/main/berkeley-function-call-leaderboard/bfcl/model_handler/oss_model/base_oss_handler.py#L84-L86)是起vllm server的。具体怎么加载模型这是vllm的事情，我们不做特殊处理。这个Issue可能有帮助https://github.com/vllm-project/vllm/issues/2924

**Comment by belief888** [comment]
ok
