### ISSUE TITLE
[bug] OpenFunctions-v2: <Issue>本地电脑部署gorilla-llm/gorilla-openfunctions-v2模型，该模型推理生成有结果，评估有报错。

### ISSUE THREAD

**Issue by belief888** [ShishirPatil/gorilla#798]
本地电脑gorilla-llm/gorilla-openfunctions-v2模型vllm推理生成（取一条数据）：
{"id": "simple_1", "result": " <<function>>math.factorial(number=5)", "input_token_count": 105, "output_token_count": 13, "latency": 4.846866846084595}
以上是bfcl模型gorilla-openfunctions-v2推理生成的结果，根据生成的结果进行评估，评估结果报如下错误：
{"id": 1, "model_name": "gorilla-openfunctions-v2", "test_category": "simple", "valid": false, "error": ["Invalid syntax. Failed to decode AST. invalid syntax (<unknown>, line 1)"], "error_type": "ast_decoder:decoder_failed", "prompt": {"id": "simple_0", "question": [[{"role": "user", "content": "Find the area of a triangle with a base of 10 units and height of 5 units."}]], "function": [{"name": "calculate_triangle_area", "description": "Calculate the area of a triangle given its base and height.", "parameters": {"type": "dict", "properties": {"base": {"type": "integer", "description": "The base of the triangle."}, "height": {"type": "integer", "description": "The height of the triangle."}, "unit": {"type": "string", "description": "The unit of measure (defaults to 'units' if not specified)"}}, "required": ["base", "height"]}}]}, "model_result_raw": " <<function>>calculate_triangle_area(base=10, height=5)", "possible_answer": [{"calculate_triangle_area": {"base": [10], "height": [5], "unit": ["units", ""]}}]}

**Comment by belief888** [comment]
handler_map.py这个文件local_inference_handler_map加入"gorilla-openfunctions-v2": Local_GorillaHandler,并新增
一个类Local_GorillaHandler，继承OSSHandler，定义def _format_prompt(self, messages, functions)方法。

**Comment by belief888** [comment]
handler_map.py这个文件local_inference_handler_map加入"gorilla-openfunctions-v2": Local_GorillaHandler,并新增
一个类Local_GorillaHandler，继承OSSHandler，定义def _format_prompt(self, messages, functions)方法。请问有啥原因造成评估结果全部报错

**Comment by belief888** [comment]
模型vllm生成的结果:
{"id": "simple_0", "result": " <<function>>calculate_triangle_area(base=10, height=5)", "input_token_count": 165, "output_token_count": 19, "latency": 5.586110830307007}
{"id": "simple_1", "result": " <<function>>math.factorial(number=5)", "input_token_count": 105, "output_token_count": 13, "latency": 4.846866846084595}
{"id": "simple_2", "result": " <<function>>math.hypot(x=4, y=5)", "input_token_count": 191, "output_token_count": 17, "latency": 5.301837921142578}
{"id": "simple_3", "result": " <<function>>algebra.quadratic_roots(a=1, b=-3, c=2)", "input_token_count": 164, "output_token_count": 22, "latency": 5.993322134017944}
{"id": "simple_4", "result": " <<function>>solve_quadratic_equation(a=2, b=6, c=5)", "input_token_count": 153, "output_token_count": 22, "latency": 6.000243186950684}

**Comment by HuanzhiMao** [comment]
> "error_type": "ast_decoder:decoder_failed"

你本地跑openfunction的话 `decode_ast`, `decode_exec`那些都得相对应的调整，另外你还得额外视情况覆盖`_prompting`的那些method ([这些](https://github.com/ShishirPatil/gorilla/blob/main/berkeley-function-call-leaderboard/bfcl/model_handler/oss_model/base_oss_handler.py#L306-L365)), 因为本地的模型都是走`_prompting`的，但是openfunction的handler默认是用API的（是用`_FC`的），所以`_prompting`的那些都需要你补上才行。

**Comment by belief888** [comment]
请问具体相关代码可以分享出来吗？

**Comment by HuanzhiMao** [comment]
> 请问具体相关代码可以分享出来吗？

这个我们目前还没写过; 我们openfunctions一直都是用默认的API跑的。我的意识是如果你想本地跑openfunctions的话，你需要把它当成一个全新的模型去写个新的handler，现有的那个gorilla handler不适用（都得重写）。

**Comment by belief888** [comment]
请问openfunction 的_prompting方式跟_FC主要区别是什么？
