### ISSUE TITLE
After using raft_local.py in Gorilla to generate the training dataset, it seems that the subsequent code for fine-tuning the model is not included or visible

### ISSUE THREAD

**Issue by belief888** [ShishirPatil/gorilla#807]
After using raft_local.py in Gorilla to generate the training dataset, it seems that the subsequent code for fine-tuning the model is not included or visible。
Could you provide more details about this part? Specifically, after using raft_local.py to generate the training dataset, are there any specific steps, configurations, or scripts that are missing for fine-tuning the model? If so, clarifying these details would help address the issue more effectively.

**Comment by belief888** [comment]
The code for training the model on a local computer. not on Microsoft AI Studio .

**Comment by ShishirPatil** [comment]
Hey @belief888 for finetuning, we should be compatible with most finetuning pipelines once you generate the dataset. [Fastchat](https://github.com/lm-sys/FastChat) is one of repos that has worked reliably for us in the past (and supports local training). Can you try this out? 

I'll close this issue for now, but please feel free to re-open if this doesn't solve it.
