### ISSUE TITLE
[feature] - Change the Gorilla picture to the one of ones below (if you like it)

### ISSUE THREAD

**Issue by Chibionos** [ShishirPatil/gorilla#82]
![6](https://github.com/ShishirPatil/gorilla/assets/3019880/0512caa6-b4c6-4472-95c8-7081cf7f399e)
![5](https://github.com/ShishirPatil/gorilla/assets/3019880/309b1087-67ef-4310-a211-c225bc6eba07)
![4](https://github.com/ShishirPatil/gorilla/assets/3019880/21cec933-afc1-46c6-a264-0bdd63d7ee55)
![Gorilla2](https://github.com/ShishirPatil/gorilla/assets/3019880/6da427ff-9396-43c3-83ba-8e97417eae76)
![Gorilla1](https://github.com/ShishirPatil/gorilla/assets/3019880/188dbdbf-e13a-480e-b0ce-ecfafa7f24e1)
![Gorilla](https://github.com/ShishirPatil/gorilla/assets/3019880/c894d085-39e8-4ecd-b3a7-00b19db1b053)

**Comment by ShishirPatil** [comment]
Thanks for sharing these @Chibionos Just so people don't get confused if its a different project with a logo change, I think we might just retain the current one. Thanks for sharing though!
