### ISSUE TITLE
[BFCL] Request commit hash for the live leaderboard numbers 

### ISSUE THREAD

**Issue by sileix** [ShishirPatil/gorilla#821]
Previously I notice some mismatch in my local evaluation results and results on the leaderboard. It turns out to be I'm not using the same version as the live leaderboard. (https://github.com/ShishirPatil/gorilla/issues/773) 

I noticed the same issue again with the current main branch. Is it possible to provide the exact commit hash that the current leaderboard used for evaluation? Ideally, I think it would be nice to include the hash info along side the leaderboard for every update. This will make it much easier to reproduce the numbers and compare with local models that are still work in progress.

**Comment by HuanzhiMao** [comment]
Hi, the commit hash is included at the end of the leaderboard section. 
<img width="1208" alt="image" src="https://github.com/user-attachments/assets/b49efbff-d504-4253-a49e-e048c35d6db7">
It is also included in the leaderboard update PR title. #800

**Comment by sileix** [comment]
Oh thank you! Sorry I missed that.
