### ISSUE TITLE
[BFCL] mismatch score for llama 3.1 8b instruct model

### ISSUE THREAD

**Issue by jielou** [ShishirPatil/gorilla#827]
**Describe the issue**
in the leaderboard, non live simple score for llama 3.1 8b instruct model is 72.58, however, in the [json file](https://github.com/HuanzhiMao/BFCL-Result/blob/main/2024-12-06/score/meta-llama_Llama-3.1-8B-Instruct/BFCL_v3_simple_score.json), I saw 0.9375. it also matched what I ran the HF model. Did I miss anything or the score was just wrong in the leaderboard?

**Proposed Changes**
update the leaderboard

**Comment by HuanzhiMao** [comment]
Hi @jielou,
Thanks for the issue. The leaderboard score is accurate. The simple category on the leaderboard consists of `simple`, `java`, and `javascript` and it's an unweighted average of the three. We will update the naming to avoid confusion.

**Comment by HuanzhiMao** [comment]
Update:
We provided a full leaderboard score composition breakdown [here](https://gorilla.cs.berkeley.edu/blogs/13_bfcl_v3_multi_turn.html#leaderboard-composition). Please let me know if you have more questions.

**Comment by jielou** [comment]
thanks for the reply and taking the prompt action. closed the issue!
