### ISSUE TITLE
[BFCL] Berkeley Function Calling Leaderboard update frequency

### ISSUE THREAD

**Issue by JIAtu-Lin** [ShishirPatil/gorilla#841]
hello, Can you tell me when the Berkeley Function Calling Leaderboard will be updated? How often is the update frequency? It seems like half a month has passed since the last update

**Comment by HuanzhiMao** [comment]
Hi @JIAtu-Lin ,

We’re planning to update the leaderboard this week, within the next two or three days. Moving forward, we’ll try to update it as soon as possible to keep the information current and models up-to-date.

**Comment by HuanzhiMao** [comment]
Apologies for the delay. The leaderboard has been updated in #845
